### ISSUE TITLE
Pypi version?

### ISSUE THREAD

**Issue by bird-in-hat** [arrobalytics/django-blog-zinnia#2]
Hello. Can you upload your fork to pypi please!? Its feels unsafe to use git repository link

**Comment by gtoffoli** [comment]
Hi. I understand that you feel it is worthwhile to create a new pypi version from the arrobalytics fork, with my additions from last year. But I don't have a pypi account, I'm not familiar with pypi package generation, and I'm too old to take care of its maintenance. Couldn't you take charge of the whole thing or ask someone else? Thanks!
